targetInstance: ${TEST_URL:http://localhost:8089}

ccdGatewayUrl: ${CCD_GW_URL:http://localhost:3453}
document_management.url: ${DM_URL:http://127.0.0.1:4506}

spring:
  cache:
    cache-names: legalRepTokenCache, systemTokenCache
    caffeine:
      spec: expireAfterWrite=3600s
