feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000

targetInstance: ${TEST_URL:http://localhost:8089}

ccdGatewayUrl: ${CCD_GW_URL:http://localhost:3453}
document_management.url: ${DM_URL:http://127.0.0.1:4506}

