version: '2.1'

services:
  ia-case-access-api:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmcts/ia-case-access-api
    container_name: ia-case-access-api
    environment:
      JAVA_OPTS:
      # these environment variables are used by java-logging library
      JSON_CONSOLE_PRETTY_PRINT:
      ROOT_APPENDER:
      ROOT_LOGGING_LEVEL:
      REFORM_SERVICE_TYPE:
      REFORM_SERVICE_NAME:
      REFORM_TEAM:
      REFORM_ENVIRONMENT:
      LOGBACK_DATE_FORMAT:
      LOGBACK_REQUIRE_THREAD:
      LOGBACK_REQUIRE_ALERT_LEVEL: "false"
      LOGBACK_REQUIRE_ERROR_CODE: "false"
      # Application environment variables
      S2S_URL: http://service-auth-provider-api:8080
      IA_S2S_MICROSERVICE:
      IA_S2S_SECRET:

    external_links:
      - idam-api
      - service-auth-provider-api
    ports:
      - ${SERVER_PORT:-8089}:${SERVER_PORT:-8089}
networks:
  compose_default:
    external: true
