server:
  port: 8089

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

  health:
    probes:
      enabled: true

spring:
  application:
    name: IA Case Access API
  main:
    allow-bean-definition-overriding: true
  jackson.date-format: yyyy-MM-dd

health:
  probes:
    enabled: true
  services:
    idam:
      uri: ${IDAM_URL:http://127.0.0.1:5000}/health
      response: '"status":"UP"'
    serviceAuth:
      uri: ${S2S_URL:http://127.0.0.1:4502}/health
      response: '"status":"UP"'
    ccd:
      uri: ${CCD_URL:http://127.0.0.1:4452}/health
      response: '"status":"UP"'

requestPagination.maxRecords: 100
executorService.threadPoolSize: 10

security:
  anonymousPaths:
    - "/"
    - "/health"
    - "/health/liveness"
    - "/health/readiness"
    - "/loggers/**"
    - "/swagger-ui.html"
    - "/swagger-resources/**"
    - "/v2/api-docs"
    - "/webjars/springfox-swagger-ui/**"
    - "/favicon.ico"
    - "/csrf"
    - "/testing-support/**"

auth.provider.service.client.baseUrl: ${S2S_URL:http://127.0.0.1:4502}

idam:
  baseUrl: ${IDAM_URL:http://127.0.0.1:5000}
  redirectUrl: ${IA_IDAM_REDIRECT_URI:http://localhost:3002/oauth2/callback}
  system:
    username: ${IA_SYSTEM_ACCESS_USERNAME:}
    password: ${IA_SYSTEM_ACCESS_PASSWORD:}
    scope: "openid profile roles"
    client-id: ${IA_IDAM_CLIENT_ID:ia}
    client-secret: ${IA_IDAM_SECRET:something}
  s2s-auth:
    totp_secret: ${IA_S2S_SECRET:}
    microservice: ${IA_S2S_MICROSERVICE:ia}
    url: ${S2S_URL:http://127.0.0.1:4502}
  s2s-authorised:
    services: ${IA_S2S_AUTHORIZED_SERVICES:iac,payment_app}

ccd:
  case-data-api:
    url: ${CCD_URL:http://127.0.0.1:4452}
